apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-care
  labels:
    app: health-care
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-care
  template:
    metadata:
      labels:
        app: health-care
    spec:
      containers:
      - name: health-care
        image: swetarani23/health-care-app:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: health-care
  labels:
    app: health-care
spec:
  selector:
    app: health-care

  type: NodePort
  ports:
  - nodePort: 31002
    port: 8080
    targetPort: 8080
