apiVersion: apps/v1
kind: Deployment
metadata:
  name:  health-care-deploy
  labels:
    app: health-care-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-care-app
  template:
    metadata:
      labels:
        app: health-care-app
    spec:
      containers:
      - name: health-care-container
        image: swetarani23/health-care-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: health-care-np-service
  labels:
    app: health-care-app
spec:
  selector:
    app: health-care-app

  type: NodePort
  ports:
  - nodePort: 31002
    port: 8080
    targetPort: 8080
